### ISSUE TITLE
Can't log in — macOS Mojave 10.14.2, @fine.sh/cli@0.0.10, node v11.6.0

### ISSUE THREAD

**Issue by rdyson** [just-fine/fine.sh-cli#13]
Type:  
- [x] Bug  
- [ ] Feature  
- [ ] Help   

Version & Environment:  

* macOS Mojave 10.14.2
* @fine.sh/cli@0.0.10
* node v11.6.0

Description:  

I can deploy a site without logging in using `npx @fine.sh/cli`, but after installing fine using `npm i @fine.sh/cli -g` and issuing the `fine login` command, I receive an error after attempting to verify login credentials that reads "some exceptions occurred to the server".

Screenshots:  

[Video here](https://v.usetapes.com/JxHaoZIKEO)

**Comment by WittBulter** [comment]
thanks for your issue and video.
it looks like the server error in getting token from GitHub, can you open the browser console (`command + option + i`) when you validate in web page? the `console network` also needs to return more error messages.

i'm trying to replicate this problem.

**Comment by rdyson** [comment]
Sure thing, happy to help! 

The full response message is as follows:
```message: "update_user err, UsageError: Invalid new record.↵Details:↵  New record contains the wrong type of data for property `email`.  Specified value (`null`) is not a valid `email`.  Even though this attribute is optional, it still does not allow `null` to be explicitly set, because `null` is not valid vs. the expected type: 'string'.  Instead, to indicate "voidness", please set the value for this attribute to the base value for its type, `''` (empty string).  Or, if you specifically need to save `null`, then change this attribute to either `type: 'json'` or `type: 'ref'`.  Also note: Since this attribute does not define a `defaultsTo`, the base value will be used as an implicit default if `email` is omitted when creating a record.↵"```

Network > Response
<img width="1920" alt="screen shot 2019-01-15 at 12 08 43 pm" src="https://user-images.githubusercontent.com/360430/51197108-a6a20680-18be-11e9-84d1-bc3ae91e7063.png">

Network > Preview
<img width="1920" alt="screen shot 2019-01-15 at 12 08 30 pm" src="https://user-images.githubusercontent.com/360430/51197111-a6a20680-18be-11e9-9ae7-17c969f199ca.png">

Network > Headers
<img width="1920" alt="screen shot 2019-01-15 at 12 08 10 pm" src="https://user-images.githubusercontent.com/360430/51197112-a73a9d00-18be-11e9-81fc-320241c36c3c.png">

**Comment by WittBulter** [comment]
@rdyson 
i just redeployed, it seems that this problem should be solved. can you try once?

**Comment by rdyson** [comment]
Great, it works now! Thanks for an awesome product. I'm excited to play around with it. I'm closing this issue. I'm happy to QA in the future if you need it.

**Comment by WittBulter** [comment]
your issue is very professional, thank you very much for your information on this issue.
welcome to help fine, you can focus on this project, every time Fine releases a preview version, you are welcome to experience it.

we use this [package](https://www.npmjs.com/package/@finesh/cli) as the experience address, you can keep in touch with us on github issues. 

thank you again for your contribution.
