### ISSUE TITLE
HELP BLOCK

### ISSUE THREAD

**Issue by cute-angelia** [just-fine/fine.sh-cli#16]
→ fine
⠙ 2 files awaiting processing...
 blocked
✖ upload failure.

**Comment by cute-angelia** [comment]
什么意思~ 色情内容 呵呵

**Comment by WittBulter** [comment]
@cute-angelia 
已将试图发布有关违禁信息的页面源内容，您的邮箱、真实姓名、常用 IP 地址等提交给网警。
